apiVersion: v2
name: multi-agent-system
description: Multi-Agent 시스템 Helm Chart (MoE 패턴 기반)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - multi-agent
  - moe
  - kubernetes
  - ai
  - automation
maintainers:
  - name: Development Team
    email: dev@example.com

