# 프로덕션 환경용 설정

global:
  environment: production
  namespace: agent-system

imageRegistry:
  url: your-registry.azurecr.io  # 또는 ECR, GCR 등
  pullPolicy: Always

routerAgent:
  replicaCount: 3
  
  image:
    repository: router-agent
    tag: "1.0.0"  # 명시적 버전 사용
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 20

sdbAgent:
  replicaCount: 2
  
  image:
    repository: sdb-agent
    tag: "1.0.0"
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2000m"
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 20

ingress:
  enabled: true
  className: alb  # AWS ALB, GCP: gce, Azure: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # AWS ALB 사용 시:
    # kubernetes.io/ingress.class: alb
    # alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/target-type: ip
  
  hosts:
    - host: agents.your-domain.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: router-agent-svc
              port: 5000
  
  tls:
    - secretName: agent-tls
      hosts:
        - agents.your-domain.com

monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true

networkPolicy:
  enabled: true  # 프로덕션에서는 활성화

