version: '3.8'

services:
  sdb-agent:
    build: .
    container_name: sdb-generation-agent
    networks:
      - sdb-network
    ports:
      - "5000:5000"
    environment:
      # Flask 설정
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      
      # Bitbucket 설정 (실제 값으로 교체 필요)
      - BITBUCKET_URL=https://api.bitbucket.org
      - BITBUCKET_USERNAME=${BITBUCKET_USERNAME}
      - BITBUCKET_APP_PASSWORD=${BITBUCKET_APP_PASSWORD}
      - WORKSPACE=${BITBUCKET_WORKSPACE}
      - REPOSITORY_SLUG=${BITBUCKET_REPOSITORY}
      
      # OpenAI 설정 (선택사항)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4-turbo-preview
      
    volumes:
      # 개발 중 코드 변경사항 실시간 반영
      - ./app:/app/app
      - ./few_shot_examples.json:/app/few_shot_examples.json
      
    restart: unless-stopped
    
    # 헬스체크
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Cloudflare Tunnel (Quick Tunnel - 임시 URL)
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: sdb-agent-tunnel-quick
    networks:
      - sdb-network
    command: tunnel --no-autoupdate --url http://sdb-agent:5000
    depends_on:
      sdb-agent:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - cloudflare

networks:
  sdb-network:
    driver: bridge
